/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_ABSTRACT_CLASS(hkWorldMemoryAvailableWatchDog)
HK_ABSTRACT_CLASS(hkpAction)
HK_ABSTRACT_CLASS(hkpArrayAction)
HK_ABSTRACT_CLASS(hkpBinaryAction)
HK_ABSTRACT_CLASS(hkpBreakableBody)
HK_ABSTRACT_CLASS(hkpBreakableMaterial)
HK_ABSTRACT_CLASS(hkpBreakableMultiMaterial)
HK_ABSTRACT_CLASS(hkpConstraintChainData)
HK_ABSTRACT_CLASS(hkpMotion)
HK_ABSTRACT_CLASS(hkpPhantom)
HK_ABSTRACT_CLASS(hkpShapePhantom)
HK_ABSTRACT_CLASS(hkpUnaryAction)
HK_ABSTRACT_CLASS(hkpWorldObject)
HK_CLASS(hkpAabbPhantom)
HK_CLASS(hkpBallSocketChainData)
HK_CLASS(hkpBoxMotion)
HK_CLASS(hkpBreakableBodyController)
HK_CLASS(hkpBreakableConstraintData)
HK_CLASS(hkpBreakableMultiMaterialInverseMapping)
HK_CLASS(hkpBreakableShape)
HK_CLASS(hkpCachingShapePhantom)
HK_CLASS(hkpCharacterMotion)
HK_CLASS(hkpConstraintChainInstance)
HK_CLASS(hkpConstraintChainInstanceAction)
HK_CLASS(hkpConstraintCollisionFilter)
HK_CLASS(hkpConstraintInstance)
HK_CLASS(hkpDefaultWorldMemoryWatchDog)
HK_CLASS(hkpEntity)
HK_CLASS(hkpExtendedMeshShapeBreakableMaterial)
HK_CLASS(hkpFixedRigidMotion)
HK_CLASS(hkpGenericConstraintData)
HK_CLASS(hkpKeyframedRigidMotion)
HK_CLASS(hkpListShapeBreakableMaterial)
HK_CLASS(hkpMalleableConstraintData)
HK_CLASS(hkpMaxSizeMotion)
HK_CLASS(hkpPairCollisionFilter)
HK_CLASS(hkpPhysicsSystem)
HK_CLASS(hkpRigidBody)
HK_CLASS(hkpSimpleBreakableMaterial)
HK_CLASS(hkpSimpleShapePhantom)
HK_CLASS(hkpSimulation)
HK_CLASS(hkpSphereMotion)
HK_CLASS(hkpStaticCompoundShapeBreakableMaterial)
HK_CLASS(hkpStiffSpringChainData)
HK_CLASS(hkpThinBoxMotion)
HK_CLASS(hkpWorld)
HK_CLASS(hkpWorldCinfo)
HK_STRUCT(hkpBallSocketChainDataConstraintInfo)
HK_STRUCT(hkpBreakableMultiMaterialInverseMappingDescriptor)
HK_STRUCT(hkpCenterOfMassChangerModifierConstraintAtom)
HK_STRUCT(hkpConstraintInstanceSmallArraySerializeOverrideType)
HK_STRUCT(hkpEntityExtendedListeners)
HK_STRUCT(hkpEntitySmallArraySerializeOverrideType)
HK_STRUCT(hkpEntitySpuCollisionCallback)
HK_STRUCT(hkpGenericConstraintDataScheme)
HK_STRUCT(hkpGenericConstraintDataSchemeConstraintInfo)
HK_STRUCT(hkpIgnoreModifierConstraintAtom)
HK_STRUCT(hkpMassChangerModifierConstraintAtom)
HK_STRUCT(hkpMaterial)
HK_STRUCT(hkpModifierConstraintAtom)
HK_STRUCT(hkpMovingSurfaceModifierConstraintAtom)
HK_STRUCT(hkpPairCollisionFilterMapPairFilterKeyOverrideType)
HK_STRUCT(hkpSimpleContactConstraintAtom)
HK_STRUCT(hkpSimpleShapePhantomCollisionDetail)
HK_STRUCT(hkpSoftContactModifierConstraintAtom)
HK_STRUCT(hkpStiffSpringChainDataConstraintInfo)
HK_STRUCT(hkpViscousSurfaceModifierConstraintAtom)
#ifndef HK_EXCLUDE_FEATURE_hkpPoweredChainData
HK_CLASS(hkpPoweredChainData)
HK_STRUCT(hkpPoweredChainDataConstraintInfo)
#endif

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
