/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

#ifndef HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE
#error HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE must be defined
#endif


//HK_REFLECTION_PARSER_EXCLUDE_FILE

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_300
HK_CLASS_UPDATE_INFO(300,310)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_310
HK_CLASS_UPDATE_INFO(310,320)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_320
HK_CLASS_UPDATE_INFO(320,330a2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_330a2
HK_CLASS_UPDATE_INFO(330a2,330b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_330b1
HK_CLASS_UPDATE_INFO(330b1,330b2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_330b2
HK_CLASS_UPDATE_INFO(330b2,330r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_330r1
HK_CLASS_UPDATE_INFO(330r1,400b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_400b1
HK_CLASS_UPDATE_INFO(400b1,400b2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_400b2
HK_CLASS_UPDATE_INFO(400b2,400r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_400r1
HK_CLASS_UPDATE_INFO(400r1,402r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_402r1
HK_CLASS_UPDATE_INFO(402r1,403r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_403r1
HK_CLASS_UPDATE_INFO(403r1,410b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_410b1
HK_CLASS_UPDATE_INFO(410b1,410r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_410r1
HK_CLASS_UPDATE_INFO(410r1,450b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_450b1
HK_CLASS_UPDATE_INFO(450b1,450r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_450r1
HK_CLASS_UPDATE_INFO(450r1,451r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_451r1
HK_CLASS_UPDATE_INFO(451r1,452r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_452r1
HK_CLASS_UPDATE_INFO(452r1,460b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_460b1
HK_CLASS_UPDATE_INFO(460b1,460b2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_460b2
HK_CLASS_UPDATE_INFO(460b2,460r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_460r1
HK_CLASS_UPDATE_INFO(460r1,461r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_461r1
HK_CLASS_UPDATE_INFO(461r1,500b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_500b1
HK_CLASS_UPDATE_INFO(500b1,500r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_500r1
HK_CLASS_UPDATE_INFO(500r1,510r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_510r1
HK_CLASS_UPDATE_INFO(510r1,550b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_550b1
HK_CLASS_UPDATE_INFO(550b1,550b2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_550b2
HK_CLASS_UPDATE_INFO(550b2,550r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_550r1
HK_CLASS_UPDATE_INFO(550r1,600b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_600b1
HK_CLASS_UPDATE_INFO(600b1,600b2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_600b2
HK_CLASS_UPDATE_INFO(600b2,600r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_600r1
HK_CLASS_UPDATE_INFO(600r1,610r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_610r1
HK_CLASS_UPDATE_INFO(610r1,650b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_650b1
HK_CLASS_UPDATE_INFO(650b1,650r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_650r1
HK_CLASS_UPDATE_INFO(650r1,660b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_660b1
HK_CLASS_UPDATE_INFO(660b1,660r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_660r1
HK_CLASS_UPDATE_INFO(660r1,700b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_700b1
HK_CLASS_UPDATE_INFO(700b1,700r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_700r1
HK_CLASS_UPDATE_INFO(700r1,710r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_710r1
HK_CLASS_UPDATE_INFO(710r1,201010r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201010r1
HK_CLASS_UPDATE_INFO(201010r1,201020r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201020r1
HK_CLASS_UPDATE_INFO(201020r1,201110r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201110r1
HK_CLASS_UPDATE_INFO(201110r1,201120r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201120r1
HK_CLASS_UPDATE_INFO(201120r1,201130r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201130r1
HK_CLASS_UPDATE_INFO(201130r1,201131r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201131r1
HK_CLASS_UPDATE_INFO(201131r1,201210r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201210r1
HK_CLASS_UPDATE_INFO(201210r1,201220r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201220r1
HK_CLASS_UPDATE_INFO(201220r1,201221r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201221r1
HK_CLASS_UPDATE_INFO(201221r1,Current)
#endif

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
