/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

#ifndef HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE
#error HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE must be defined
//#define HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE 0
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_300
HK_HAVOK_CLASSES_VERSION(300)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_310
HK_HAVOK_CLASSES_VERSION(310)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_320
HK_HAVOK_CLASSES_VERSION(320)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_330a2
HK_HAVOK_CLASSES_VERSION(330a2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_330b1
HK_HAVOK_CLASSES_VERSION(330b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_330b2
HK_HAVOK_CLASSES_VERSION(330b2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_330r1
HK_HAVOK_CLASSES_VERSION(330r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_400b1
HK_HAVOK_CLASSES_VERSION(400b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_400b2
HK_HAVOK_CLASSES_VERSION(400b2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_400r1
HK_HAVOK_CLASSES_VERSION(400r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_402r1
HK_HAVOK_CLASSES_VERSION(402r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_403r1
HK_HAVOK_CLASSES_VERSION(403r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_410b1
HK_HAVOK_CLASSES_VERSION(410b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_410r1
HK_HAVOK_CLASSES_VERSION(410r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_450b1
HK_HAVOK_CLASSES_VERSION(450b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_450r1
HK_HAVOK_CLASSES_VERSION(450r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_451r1
HK_HAVOK_CLASSES_VERSION(451r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_452r1
HK_HAVOK_CLASSES_VERSION(452r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_460b1
HK_HAVOK_CLASSES_VERSION(460b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_460b2
HK_HAVOK_CLASSES_VERSION(460b2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_460r1
HK_HAVOK_CLASSES_VERSION(460r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_461r1
HK_HAVOK_CLASSES_VERSION(461r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_500b1
HK_HAVOK_CLASSES_VERSION(500b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_500r1
HK_HAVOK_CLASSES_VERSION(500r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_510r1
HK_HAVOK_CLASSES_VERSION(510r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_550b1
HK_HAVOK_CLASSES_VERSION(550b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_550b2
HK_HAVOK_CLASSES_VERSION(550b2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_550r1
HK_HAVOK_CLASSES_VERSION(550r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_600b1
HK_HAVOK_CLASSES_VERSION(600b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_600b2
HK_HAVOK_CLASSES_VERSION(600b2)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_600r1
HK_HAVOK_CLASSES_VERSION(600r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_610r1
HK_HAVOK_CLASSES_VERSION(610r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_650b1
HK_HAVOK_CLASSES_VERSION(650b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_650r1
HK_HAVOK_CLASSES_VERSION(650r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_660b1
HK_HAVOK_CLASSES_VERSION(660b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_660r1
HK_HAVOK_CLASSES_VERSION(660r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_700b1
HK_HAVOK_CLASSES_VERSION(700b1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_700r1
HK_HAVOK_CLASSES_VERSION(700r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_710r1
HK_HAVOK_CLASSES_VERSION(710r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201010r1
HK_HAVOK_CLASSES_VERSION(201010r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201020r1
HK_HAVOK_CLASSES_VERSION(201020r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201110r1
HK_HAVOK_CLASSES_VERSION(201110r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201120r1
HK_HAVOK_CLASSES_VERSION(201120r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201130r1
HK_HAVOK_CLASSES_VERSION(201130r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201131r1
HK_HAVOK_CLASSES_VERSION(201131r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201210r1
HK_HAVOK_CLASSES_VERSION(201210r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201220r1
HK_HAVOK_CLASSES_VERSION(201220r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_201221r1
HK_HAVOK_CLASSES_VERSION(201221r1)
#endif

#if HK_SERIALIZE_MIN_COMPATIBLE_VERSION_INTERNAL_VALUE <= HK_HAVOK_VERSION_Current
HK_HAVOK_CLASSES_VERSION(Current)
#endif

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
