/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */
//
// NOTE: This file is autogenerated. Any changes will be lost.
//
//HK_REFLECTION_PARSER_EXCLUDE_FILE
HK_TEST_DECLARE(htl_main)
HK_TEST_DECLARE(compression_main)
HK_TEST_DECLARE(maps_main)
HK_TEST_DECLARE(object_array_main)
HK_TEST_DECLARE(oneAxisSweep_main)
HK_TEST_DECLARE(findIndex_main)
HK_TEST_DECLARE(sort_main)
HK_TEST_DECLARE(allocator_test_main)
HK_TEST_DECLARE(baseTypes_main)
HK_TEST_DECLARE(nonstandard_main)
HK_TEST_DECLARE(array_main)
HK_TEST_DECLARE(bitfield_main)
HK_TEST_DECLARE(fixed_size_block_list_main)
HK_TEST_DECLARE(freeListArray_main)
HK_TEST_DECLARE(localarray_main)
HK_TEST_DECLARE(minHeap_main)
HK_TEST_DECLARE(pointerMultiMap_main)
HK_TEST_DECLARE(pointermap_main)
HK_TEST_DECLARE(queue_main)
HK_TEST_DECLARE(set_main)
HK_TEST_DECLARE(smallarray_main)
HK_TEST_DECLARE(stringmap_main)
HK_TEST_DECLARE(tree_main)
HK_TEST_DECLARE(monitors_main)
HK_TEST_DECLARE(fileops_main)
HK_TEST_DECLARE(convertCS_main)
HK_TEST_DECLARE(floatDouble_main)
HK_TEST_DECLARE(mathStream_main)
HK_TEST_DECLARE(matrix6_main)
HK_TEST_DECLARE(mathutil_main)
HK_TEST_DECLARE(rotation_main)
HK_TEST_DECLARE(swepttransform_main)
HK_TEST_DECLARE(fourTransposedPoints_main)
HK_TEST_DECLARE(VectorUint4_main)
HK_TEST_DECLARE(LargeInt_main)
HK_TEST_DECLARE(mathfunc_main)
HK_TEST_DECLARE(matrix3_main)
HK_TEST_DECLARE(matrix4_main)
HK_TEST_DECLARE(misc_main)
HK_TEST_DECLARE(mxvector_main)
HK_TEST_DECLARE(qstransform_main)
HK_TEST_DECLARE(quaternion_main)
HK_TEST_DECLARE(simdreal_main)
HK_TEST_DECLARE(transform_main)
HK_TEST_DECLARE(vector3_main)
HK_TEST_DECLARE(vector3util_main)
HK_TEST_DECLARE(allocators_test)
HK_TEST_DECLARE(lifoallocator_main)
HK_TEST_DECLARE(mem_tst_main)
HK_TEST_DECLARE(multithread_tst_main)
HK_TEST_DECLARE(ParserTest_main)
HK_TEST_DECLARE(crc32_main)
HK_TEST_DECLARE(filesystem_main)
HK_TEST_DECLARE(memoryTrack_main)
HK_TEST_DECLARE(stream_main)
HK_TEST_DECLARE(string_main)
HK_TEST_DECLARE(blank_main)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
