//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _lock {
            get {
                object obj = ResourceManager.GetObject("lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_zone {
            get {
                object obj = ResourceManager.GetObject("add_zone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap align_16 {
            get {
                object obj = ResourceManager.GetObject("align_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap align_normal {
            get {
                object obj = ResourceManager.GetObject("align_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_blue {
            get {
                object obj = ResourceManager.GetObject("arrow_down_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_green_down {
            get {
                object obj = ResourceManager.GetObject("arrow_green_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_blue {
            get {
                object obj = ResourceManager.GetObject("arrow_up_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_16x16 {
            get {
                object obj = ResourceManager.GetObject("asset_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_24x24 {
            get {
                object obj = ResourceManager.GetObject("asset_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_32x32 {
            get {
                object obj = ResourceManager.GetObject("asset_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_library_16x16 {
            get {
                object obj = ResourceManager.GetObject("asset_library_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_library_24x24 {
            get {
                object obj = ResourceManager.GetObject("asset_library_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_library_32x32 {
            get {
                object obj = ResourceManager.GetObject("asset_library_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_profile_16x16 {
            get {
                object obj = ResourceManager.GetObject("asset_profile_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_profile_24x24 {
            get {
                object obj = ResourceManager.GetObject("asset_profile_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_profile_32x32 {
            get {
                object obj = ResourceManager.GetObject("asset_profile_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_profile_manager_16x16 {
            get {
                object obj = ResourceManager.GetObject("asset_profile_manager_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_profile_manager_24x24 {
            get {
                object obj = ResourceManager.GetObject("asset_profile_manager_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asset_profile_manager_32x32 {
            get {
                object obj = ResourceManager.GetObject("asset_profile_manager_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ball_glass_blue_16 {
            get {
                object obj = ResourceManager.GetObject("ball_glass_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ball_glass_grey_16 {
            get {
                object obj = ResourceManager.GetObject("ball_glass_grey_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap breakpoint_into {
            get {
                object obj = ResourceManager.GetObject("breakpoint_into", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap breakpoint_new {
            get {
                object obj = ResourceManager.GetObject("breakpoint_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera2 {
            get {
                object obj = ResourceManager.GetObject("camera2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap child_nodes {
            get {
                object obj = ResourceManager.GetObject("child_nodes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap child_nodes_icon {
            get {
                object obj = ResourceManager.GetObject("child_nodes_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap child_nodes_rec {
            get {
                object obj = ResourceManager.GetObject("child_nodes_rec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapse_all {
            get {
                object obj = ResourceManager.GetObject("collapse_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete2 {
            get {
                object obj = ResourceManager.GetObject("delete2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expand_all {
            get {
                object obj = ResourceManager.GetObject("expand_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fit_to_size {
            get {
                object obj = ResourceManager.GetObject("fit_to_size", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags {
            get {
                object obj = ResourceManager.GetObject("flags", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_new {
            get {
                object obj = ResourceManager.GetObject("folder_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_refresh {
            get {
                object obj = ResourceManager.GetObject("folder_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frame_all {
            get {
                object obj = ResourceManager.GetObject("frame_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frame_autoselect {
            get {
                object obj = ResourceManager.GetObject("frame_autoselect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frame_selected {
            get {
                object obj = ResourceManager.GetObject("frame_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gizmo {
            get {
                object obj = ResourceManager.GetObject("gizmo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icons {
            get {
                object obj = ResourceManager.GetObject("icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap isolate_exit {
            get {
                object obj = ResourceManager.GetObject("isolate_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap isolate_selection {
            get {
                object obj = ResourceManager.GetObject("isolate_selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lightbulb_on {
            get {
                object obj = ResourceManager.GetObject("lightbulb_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap links {
            get {
                object obj = ResourceManager.GetObject("links", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_open {
            get {
                object obj = ResourceManager.GetObject("lock_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_view {
            get {
                object obj = ResourceManager.GetObject("lock_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lua_blank {
            get {
                object obj = ResourceManager.GetObject("lua_blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lua_function {
            get {
                object obj = ResourceManager.GetObject("lua_function", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lua_local {
            get {
                object obj = ResourceManager.GetObject("lua_local", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lua_table {
            get {
                object obj = ResourceManager.GetObject("lua_table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lua_userdata {
            get {
                object obj = ResourceManager.GetObject("lua_userdata", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap magnet {
            get {
                object obj = ResourceManager.GetObject("magnet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manifest_settings_16x16 {
            get {
                object obj = ResourceManager.GetObject("manifest_settings_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manifest_settings_24x24 {
            get {
                object obj = ResourceManager.GetObject("manifest_settings_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manifest_settings_32x32 {
            get {
                object obj = ResourceManager.GetObject("manifest_settings_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap memory {
            get {
                object obj = ResourceManager.GetObject("memory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoveShape {
            get {
                object obj = ResourceManager.GetObject("MoveShape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap node {
            get {
                object obj = ResourceManager.GetObject("node", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste1 {
            get {
                object obj = ResourceManager.GetObject("paste1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pawn_new {
            get {
                object obj = ResourceManager.GetObject("pawn_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pawn_view {
            get {
                object obj = ResourceManager.GetObject("pawn_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pick {
            get {
                object obj = ResourceManager.GetObject("pick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RotateShape {
            get {
                object obj = ResourceManager.GetObject("RotateShape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScaleShape {
            get {
                object obj = ResourceManager.GetObject("ScaleShape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setup_grid {
            get {
                object obj = ResourceManager.GetObject("setup_grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sort_ascending {
            get {
                object obj = ResourceManager.GetObject("sort_ascending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sort_az_ascending {
            get {
                object obj = ResourceManager.GetObject("sort_az_ascending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sort_az_descending {
            get {
                object obj = ResourceManager.GetObject("sort_az_descending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sort_descending {
            get {
                object obj = ResourceManager.GetObject("sort_descending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_add {
            get {
                object obj = ResourceManager.GetObject("toolbar_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_camera {
            get {
                object obj = ResourceManager.GetObject("toolbar_camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_camera_keys {
            get {
                object obj = ResourceManager.GetObject("toolbar_camera_keys", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_camera_move {
            get {
                object obj = ResourceManager.GetObject("toolbar_camera_move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_camera_orbit {
            get {
                object obj = ResourceManager.GetObject("toolbar_camera_orbit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_camera_small {
            get {
                object obj = ResourceManager.GetObject("toolbar_camera_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_caption {
            get {
                object obj = ResourceManager.GetObject("toolbar_caption", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_check {
            get {
                object obj = ResourceManager.GetObject("toolbar_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_checkboxes {
            get {
                object obj = ResourceManager.GetObject("toolbar_checkboxes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_checks {
            get {
                object obj = ResourceManager.GetObject("toolbar_checks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_close {
            get {
                object obj = ResourceManager.GetObject("toolbar_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_copy {
            get {
                object obj = ResourceManager.GetObject("toolbar_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_cut {
            get {
                object obj = ResourceManager.GetObject("toolbar_cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_delete {
            get {
                object obj = ResourceManager.GetObject("toolbar_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_document {
            get {
                object obj = ResourceManager.GetObject("toolbar_document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_document_links {
            get {
                object obj = ResourceManager.GetObject("toolbar_document_links", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_document_settings {
            get {
                object obj = ResourceManager.GetObject("toolbar_document_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_duplicates {
            get {
                object obj = ResourceManager.GetObject("toolbar_duplicates", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_editor {
            get {
                object obj = ResourceManager.GetObject("toolbar_editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_exit {
            get {
                object obj = ResourceManager.GetObject("toolbar_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_export {
            get {
                object obj = ResourceManager.GetObject("toolbar_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_export_quick {
            get {
                object obj = ResourceManager.GetObject("toolbar_export_quick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_export_settings {
            get {
                object obj = ResourceManager.GetObject("toolbar_export_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_filter {
            get {
                object obj = ResourceManager.GetObject("toolbar_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_focus_selection {
            get {
                object obj = ResourceManager.GetObject("toolbar_focus_selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_fog {
            get {
                object obj = ResourceManager.GetObject("toolbar_fog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_folder {
            get {
                object obj = ResourceManager.GetObject("toolbar_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_folder_in {
            get {
                object obj = ResourceManager.GetObject("toolbar_folder_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_gamepad {
            get {
                object obj = ResourceManager.GetObject("toolbar_gamepad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_gizmo {
            get {
                object obj = ResourceManager.GetObject("toolbar_gizmo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_help {
            get {
                object obj = ResourceManager.GetObject("toolbar_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_hotkeys {
            get {
                object obj = ResourceManager.GetObject("toolbar_hotkeys", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_layer_zones {
            get {
                object obj = ResourceManager.GetObject("toolbar_layer_zones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_light {
            get {
                object obj = ResourceManager.GetObject("toolbar_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_light_calc {
            get {
                object obj = ResourceManager.GetObject("toolbar_light_calc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_light_reset {
            get {
                object obj = ResourceManager.GetObject("toolbar_light_reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_light_settings {
            get {
                object obj = ResourceManager.GetObject("toolbar_light_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_link {
            get {
                object obj = ResourceManager.GetObject("toolbar_link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_link_small {
            get {
                object obj = ResourceManager.GetObject("toolbar_link_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_list {
            get {
                object obj = ResourceManager.GetObject("toolbar_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_measure {
            get {
                object obj = ResourceManager.GetObject("toolbar_measure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_mobile {
            get {
                object obj = ResourceManager.GetObject("toolbar_mobile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_mobile_active {
            get {
                object obj = ResourceManager.GetObject("toolbar_mobile_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_move {
            get {
                object obj = ResourceManager.GetObject("toolbar_move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_new {
            get {
                object obj = ResourceManager.GetObject("toolbar_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_new_project {
            get {
                object obj = ResourceManager.GetObject("toolbar_new_project", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_new_scene {
            get {
                object obj = ResourceManager.GetObject("toolbar_new_scene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_open {
            get {
                object obj = ResourceManager.GetObject("toolbar_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_open_project {
            get {
                object obj = ResourceManager.GetObject("toolbar_open_project", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_open_scene {
            get {
                object obj = ResourceManager.GetObject("toolbar_open_scene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_panels {
            get {
                object obj = ResourceManager.GetObject("toolbar_panels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_paste {
            get {
                object obj = ResourceManager.GetObject("toolbar_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_play_animate {
            get {
                object obj = ResourceManager.GetObject("toolbar_play_animate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_play_editor {
            get {
                object obj = ResourceManager.GetObject("toolbar_play_editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_play_game {
            get {
                object obj = ResourceManager.GetObject("toolbar_play_game", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_plugins {
            get {
                object obj = ResourceManager.GetObject("toolbar_plugins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_post {
            get {
                object obj = ResourceManager.GetObject("toolbar_post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_properties_selection {
            get {
                object obj = ResourceManager.GetObject("toolbar_properties_selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_recent_selection {
            get {
                object obj = ResourceManager.GetObject("toolbar_recent_selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_recentproject {
            get {
                object obj = ResourceManager.GetObject("toolbar_recentproject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_recentscenes {
            get {
                object obj = ResourceManager.GetObject("toolbar_recentscenes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_redo {
            get {
                object obj = ResourceManager.GetObject("toolbar_redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_refresh {
            get {
                object obj = ResourceManager.GetObject("toolbar_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_remove {
            get {
                object obj = ResourceManager.GetObject("toolbar_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_resources {
            get {
                object obj = ResourceManager.GetObject("toolbar_resources", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_resources_small {
            get {
                object obj = ResourceManager.GetObject("toolbar_resources_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_rotate {
            get {
                object obj = ResourceManager.GetObject("toolbar_rotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_save {
            get {
                object obj = ResourceManager.GetObject("toolbar_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_save_all {
            get {
                object obj = ResourceManager.GetObject("toolbar_save_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_save_as {
            get {
                object obj = ResourceManager.GetObject("toolbar_save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_save_scene {
            get {
                object obj = ResourceManager.GetObject("toolbar_save_scene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_saveall {
            get {
                object obj = ResourceManager.GetObject("toolbar_saveall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_scale_nonuniform {
            get {
                object obj = ResourceManager.GetObject("toolbar_scale_nonuniform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_scale_nonuniform_small {
            get {
                object obj = ResourceManager.GetObject("toolbar_scale_nonuniform_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_scale_uniform {
            get {
                object obj = ResourceManager.GetObject("toolbar_scale_uniform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_scale_uniform_small {
            get {
                object obj = ResourceManager.GetObject("toolbar_scale_uniform_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_screenshot {
            get {
                object obj = ResourceManager.GetObject("toolbar_screenshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_search {
            get {
                object obj = ResourceManager.GetObject("toolbar_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_select {
            get {
                object obj = ResourceManager.GetObject("toolbar_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_selection_tools {
            get {
                object obj = ResourceManager.GetObject("toolbar_selection_tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_settings {
            get {
                object obj = ResourceManager.GetObject("toolbar_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_sky {
            get {
                object obj = ResourceManager.GetObject("toolbar_sky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_start {
            get {
                object obj = ResourceManager.GetObject("toolbar_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_stop_animate {
            get {
                object obj = ResourceManager.GetObject("toolbar_stop_animate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_stop_editor {
            get {
                object obj = ResourceManager.GetObject("toolbar_stop_editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_stop_game {
            get {
                object obj = ResourceManager.GetObject("toolbar_stop_game", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_timeofday {
            get {
                object obj = ResourceManager.GetObject("toolbar_timeofday", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_tod {
            get {
                object obj = ResourceManager.GetObject("toolbar_tod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_tool {
            get {
                object obj = ResourceManager.GetObject("toolbar_tool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_undo {
            get {
                object obj = ResourceManager.GetObject("toolbar_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_unit_scale {
            get {
                object obj = ResourceManager.GetObject("toolbar_unit_scale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_visibility {
            get {
                object obj = ResourceManager.GetObject("toolbar_visibility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_xgizmo {
            get {
                object obj = ResourceManager.GetObject("toolbar_xgizmo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_ygizmo {
            get {
                object obj = ResourceManager.GetObject("toolbar_ygizmo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar_zgizmo {
            get {
                object obj = ResourceManager.GetObject("toolbar_zgizmo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransformAsset24 {
            get {
                object obj = ResourceManager.GetObject("TransformAsset24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unload_zone {
            get {
                object obj = ResourceManager.GetObject("unload_zone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_1_1 {
            get {
                object obj = ResourceManager.GetObject("view_1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_checker {
            get {
                object obj = ResourceManager.GetObject("view_checker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_default {
            get {
                object obj = ResourceManager.GetObject("view_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_front {
            get {
                object obj = ResourceManager.GetObject("view_front", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_fullbright {
            get {
                object obj = ResourceManager.GetObject("view_fullbright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_mode {
            get {
                object obj = ResourceManager.GetObject("view_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_normalmap {
            get {
                object obj = ResourceManager.GetObject("view_normalmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_normals {
            get {
                object obj = ResourceManager.GetObject("view_normals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_overdraw {
            get {
                object obj = ResourceManager.GetObject("view_overdraw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_perspective {
            get {
                object obj = ResourceManager.GetObject("view_perspective", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_plainwhite {
            get {
                object obj = ResourceManager.GetObject("view_plainwhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_properties {
            get {
                object obj = ResourceManager.GetObject("view_properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_right {
            get {
                object obj = ResourceManager.GetObject("view_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_shaded {
            get {
                object obj = ResourceManager.GetObject("view_shaded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_solid {
            get {
                object obj = ResourceManager.GetObject("view_solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_tangents {
            get {
                object obj = ResourceManager.GetObject("view_tangents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_top {
            get {
                object obj = ResourceManager.GetObject("view_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_wireframe {
            get {
                object obj = ResourceManager.GetObject("view_wireframe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wrench {
            get {
                object obj = ResourceManager.GetObject("wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yes {
            get {
                object obj = ResourceManager.GetObject("yes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_out {
            get {
                object obj = ResourceManager.GetObject("zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
