/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_CLASS(hkAlignSceneToNodeOptions)
HK_CLASS(hkxAnimatedFloat)
HK_CLASS(hkxAnimatedMatrix)
HK_CLASS(hkxAnimatedQuaternion)
HK_CLASS(hkxAnimatedVector)
HK_CLASS(hkxAttributeHolder)
HK_CLASS(hkxBlob)
HK_CLASS(hkxBlobMeshShape)
HK_CLASS(hkxCamera)
HK_CLASS(hkxEdgeSelectionChannel)
HK_CLASS(hkxEnum)
HK_CLASS(hkxEnvironment)
HK_CLASS(hkxIndexBuffer)
HK_CLASS(hkxLight)
HK_CLASS(hkxMaterial)
HK_CLASS(hkxMaterialEffect)
HK_CLASS(hkxMaterialShader)
HK_CLASS(hkxMaterialShaderSet)
HK_CLASS(hkxMesh)
HK_CLASS(hkxMeshSection)
HK_CLASS(hkxMeshUserChannelInfo)
HK_CLASS(hkxNode)
HK_CLASS(hkxNodeSelectionSet)
HK_CLASS(hkxScene)
HK_CLASS(hkxSkinBinding)
HK_CLASS(hkxSparselyAnimatedBool)
HK_CLASS(hkxSparselyAnimatedEnum)
HK_CLASS(hkxSparselyAnimatedInt)
HK_CLASS(hkxSparselyAnimatedString)
HK_CLASS(hkxSpline)
HK_CLASS(hkxTextureFile)
HK_CLASS(hkxTextureInplace)
HK_CLASS(hkxTriangleSelectionChannel)
HK_CLASS(hkxVertexAnimation)
HK_CLASS(hkxVertexBuffer)
HK_CLASS(hkxVertexFloatDataChannel)
HK_CLASS(hkxVertexIntDataChannel)
HK_CLASS(hkxVertexSelectionChannel)
HK_CLASS(hkxVertexVectorDataChannel)
HK_STRUCT(hkxAttribute)
HK_STRUCT(hkxAttributeGroup)
HK_STRUCT(hkxEnumItem)
HK_STRUCT(hkxEnvironmentVariable)
HK_STRUCT(hkxMaterialProperty)
HK_STRUCT(hkxMaterialTextureStage)
HK_STRUCT(hkxNodeAnnotationData)
HK_STRUCT(hkxSplineControlPoint)
HK_STRUCT(hkxVertexAnimationUsageMap)
HK_STRUCT(hkxVertexBufferVertexData)
HK_STRUCT(hkxVertexDescription)
HK_STRUCT(hkxVertexDescriptionElementDecl)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
