/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_ABSTRACT_CLASS(hkpConstraintData)
HK_ABSTRACT_CLASS(hkpConstraintMotor)
HK_ABSTRACT_CLASS(hkpLimitedForceConstraintMotor)
HK_ABSTRACT_CLASS(hkpParametricCurve)
HK_CLASS(hkpBallAndSocketConstraintData)
HK_CLASS(hkpCallbackConstraintMotor)
HK_CLASS(hkpCogWheelConstraintData)
HK_CLASS(hkpDeformableFixedConstraintData)
HK_CLASS(hkpFixedConstraintData)
HK_CLASS(hkpHingeConstraintData)
HK_CLASS(hkpHingeLimitsData)
HK_CLASS(hkpLimitedHingeConstraintData)
HK_CLASS(hkpLinearClearanceConstraintData)
HK_CLASS(hkpLinearParametricCurve)
HK_CLASS(hkpPointToPathConstraintData)
HK_CLASS(hkpPointToPlaneConstraintData)
HK_CLASS(hkpPositionConstraintMotor)
HK_CLASS(hkpPrismaticConstraintData)
HK_CLASS(hkpPulleyConstraintData)
HK_CLASS(hkpRackAndPinionConstraintData)
HK_CLASS(hkpRagdollConstraintData)
HK_CLASS(hkpRagdollLimitsData)
HK_CLASS(hkpRotationalConstraintData)
HK_CLASS(hkpSpringDamperConstraintMotor)
HK_CLASS(hkpStiffSpringConstraintData)
HK_CLASS(hkpVelocityConstraintMotor)
HK_CLASS(hkpWheelConstraintData)
HK_STRUCT(hkp2dAngConstraintAtom)
HK_STRUCT(hkp3dAngConstraintAtom)
HK_STRUCT(hkpAngConstraintAtom)
HK_STRUCT(hkpAngFrictionConstraintAtom)
HK_STRUCT(hkpAngLimitConstraintAtom)
HK_STRUCT(hkpAngMotorConstraintAtom)
HK_STRUCT(hkpBallAndSocketConstraintDataAtoms)
HK_STRUCT(hkpBallSocketConstraintAtom)
HK_STRUCT(hkpBridgeAtoms)
HK_STRUCT(hkpBridgeConstraintAtom)
HK_STRUCT(hkpCogWheelConstraintAtom)
HK_STRUCT(hkpCogWheelConstraintDataAtoms)
HK_STRUCT(hkpConeLimitConstraintAtom)
HK_STRUCT(hkpConstraintAtom)
HK_STRUCT(hkpDeformableAngConstraintAtom)
HK_STRUCT(hkpDeformableFixedConstraintDataAtoms)
HK_STRUCT(hkpDeformableLinConstraintAtom)
HK_STRUCT(hkpFixedConstraintDataAtoms)
HK_STRUCT(hkpHingeConstraintDataAtoms)
HK_STRUCT(hkpHingeLimitsDataAtoms)
HK_STRUCT(hkpLimitedHingeConstraintDataAtoms)
HK_STRUCT(hkpLinConstraintAtom)
HK_STRUCT(hkpLinFrictionConstraintAtom)
HK_STRUCT(hkpLinLimitConstraintAtom)
HK_STRUCT(hkpLinMotorConstraintAtom)
HK_STRUCT(hkpLinSoftConstraintAtom)
HK_STRUCT(hkpLinearClearanceConstraintDataAtoms)
HK_STRUCT(hkpOverwritePivotConstraintAtom)
HK_STRUCT(hkpPointToPlaneConstraintDataAtoms)
HK_STRUCT(hkpPrismaticConstraintDataAtoms)
HK_STRUCT(hkpPulleyConstraintAtom)
HK_STRUCT(hkpPulleyConstraintDataAtoms)
HK_STRUCT(hkpRackAndPinionConstraintAtom)
HK_STRUCT(hkpRackAndPinionConstraintDataAtoms)
HK_STRUCT(hkpRagdollConstraintDataAtoms)
HK_STRUCT(hkpRagdollLimitsDataAtoms)
HK_STRUCT(hkpRagdollMotorConstraintAtom)
HK_STRUCT(hkpRotationalConstraintDataAtoms)
HK_STRUCT(hkpSetLocalRotationsConstraintAtom)
HK_STRUCT(hkpSetLocalTransformsConstraintAtom)
HK_STRUCT(hkpSetLocalTranslationsConstraintAtom)
HK_STRUCT(hkpSetupStabilizationAtom)
HK_STRUCT(hkpStiffSpringConstraintAtom)
HK_STRUCT(hkpStiffSpringConstraintDataAtoms)
HK_STRUCT(hkpTwistLimitConstraintAtom)
HK_STRUCT(hkpWheelConstraintDataAtoms)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
