/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_ABSTRACT_CLASS(hkaAnimatedReferenceFrame)
HK_ABSTRACT_CLASS(hkaAnimation)
HK_ABSTRACT_CLASS(hkaParameterizedReferenceFrame)
HK_CLASS(hkaAngularReferenceFrame)
HK_CLASS(hkaAnimationBinding)
HK_CLASS(hkaAnimationContainer)
HK_CLASS(hkaAnimationPreviewColorContainer)
HK_CLASS(hkaBoneAttachment)
HK_CLASS(hkaDefaultAnimatedReferenceFrame)
HK_CLASS(hkaDirectionalReferenceFrame)
HK_CLASS(hkaFootstepAnalysisInfo)
HK_CLASS(hkaFootstepAnalysisInfoContainer)
HK_CLASS(hkaInterleavedUncompressedAnimation)
HK_CLASS(hkaMeshBinding)
HK_CLASS(hkaParameterizedAnimationReferenceFrame)
HK_CLASS(hkaPredictiveCompressedAnimation)
HK_CLASS(hkaQuantizedAnimation)
HK_CLASS(hkaReferencePoseAnimation)
HK_CLASS(hkaSkeleton)
HK_CLASS(hkaSkeletonMapper)
HK_CLASS(hkaSplineCompressedAnimation)
HK_STRUCT(hkaAnnotationTrack)
HK_STRUCT(hkaAnnotationTrackAnnotation)
HK_STRUCT(hkaBone)
HK_STRUCT(hkaMeshBindingMapping)
HK_STRUCT(hkaPredictiveCompressedAnimationTrackCompressionParams)
HK_STRUCT(hkaQuantizedAnimationTrackCompressionParams)
HK_STRUCT(hkaSkeletonLocalFrameOnBone)
HK_STRUCT(hkaSkeletonMapperData)
HK_STRUCT(hkaSkeletonMapperDataChainMapping)
HK_STRUCT(hkaSkeletonMapperDataPartitionMappingRange)
HK_STRUCT(hkaSkeletonMapperDataSimpleMapping)
HK_STRUCT(hkaSkeletonPartition)
HK_STRUCT(hkaSplineCompressedAnimationAnimationCompressionParams)
HK_STRUCT(hkaSplineCompressedAnimationTrackCompressionParams)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
