/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (reflectedClasses.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

// Generated from 'Vision/Tools/SceneDataConverter/MeshFactory/hkVisionMeshShape.h'
#include <Vision/Tools/SceneDataConverter/vSceneDataConverter.h>
#include <Common/Base/Reflection/hkClass.h>
#include <Common/Base/Reflection/hkInternalClassMember.h>
#include <Common/Base/Reflection/hkTypeInfo.h>
#include <Common/Base/Reflection/Attributes/hkAttributes.h>
#include <Vision/Tools/SceneDataConverter/MeshFactory/hkVisionMeshShape.h>
#define True true
#define False false


// External pointer and enum types
extern const hkClass VGMeshClass;
extern const hkClass VGSceneClass;
extern const hkClass hkMeshMaterialClass;
extern const hkClass hkMeshSectionClass;
extern const hkClass hkReferencedObjectClass;
extern const hkClass hkVisionMeshShapeMeshClass;

//
// Class hkVisionMeshShape::Mesh
//
static const hkInternalClassMember hkVisionMeshShape_MeshClass_Members[] =
{
	{ "visionMesh", HK_NULL, HK_NULL, hkClassMember::TYPE_POINTER, hkClassMember::TYPE_VOID, 0, 0|hkClassMember::SERIALIZE_IGNORED, HK_OFFSET_OF(hkVisionMeshShape::Mesh,m_visionMesh), HK_NULL },
	{ "visionScene", HK_NULL, HK_NULL, hkClassMember::TYPE_POINTER, hkClassMember::TYPE_VOID, 0, 0|hkClassMember::SERIALIZE_IGNORED, HK_OFFSET_OF(hkVisionMeshShape::Mesh,m_visionScene), HK_NULL },
	{ "vb", HK_NULL, HK_NULL, hkClassMember::TYPE_POINTER, hkClassMember::TYPE_VOID, 0, 0|hkClassMember::SERIALIZE_IGNORED, HK_OFFSET_OF(hkVisionMeshShape::Mesh,m_vb), HK_NULL },
	{ "ib", HK_NULL, HK_NULL, hkClassMember::TYPE_POINTER, hkClassMember::TYPE_VOID, 0, 0|hkClassMember::SERIALIZE_IGNORED, HK_OFFSET_OF(hkVisionMeshShape::Mesh,m_ib), HK_NULL }
};
const hkClass hkVisionMeshShapeMeshClass(
	"hkVisionMeshShapeMesh",
	HK_NULL, // parent
	sizeof(hkVisionMeshShape::Mesh),
	HK_NULL,
	0, // interfaces
	HK_NULL,
	0, // enums
	reinterpret_cast<const hkClassMember*>(hkVisionMeshShape_MeshClass_Members),
	HK_COUNT_OF(hkVisionMeshShape_MeshClass_Members),
	HK_NULL, // defaults
	HK_NULL, // attributes
	0, // flags
	hkUint32(0) // version
	);
#ifndef HK_HKCLASS_DEFINITION_ONLY
const hkClass& HK_CALL hkVisionMeshShape::Mesh::staticClass()
{
	return hkVisionMeshShapeMeshClass;
}
HK_COMPILE_TIME_ASSERT2( \
	sizeof(hkIsVirtual(static_cast<hkVisionMeshShape::Mesh*>(0))) == sizeof(hkBool::CompileTimeFalseType), \
	REFLECTION_PARSER_VTABLE_DETECTION_FAILED );
static void HK_CALL cleanupLoadedObjecthkVisionMeshShapeMesh(void* p)
{
	static_cast<hkVisionMeshShape::Mesh*>(p)->~Mesh();
}
extern const hkTypeInfo hkVisionMeshShapeMeshTypeInfo;
const hkTypeInfo hkVisionMeshShapeMeshTypeInfo(
	"hkVisionMeshShapeMesh",
	"!hkVisionMeshShape::Mesh",
	HK_NULL,
	cleanupLoadedObjecthkVisionMeshShapeMesh,
	HK_NULL,
	sizeof(hkVisionMeshShape::Mesh)
	);
#endif

//
// Class hkVisionMeshShape
//
extern const hkClass hkxBlobMeshShapeClass;

const hkInternalClassMember hkVisionMeshShape::Members[] =
{
	{ "mesh", &hkVisionMeshShapeMeshClass, HK_NULL, hkClassMember::TYPE_STRUCT, hkClassMember::TYPE_VOID, 0, 0|hkClassMember::SERIALIZE_IGNORED, HK_OFFSET_OF(hkVisionMeshShape,m_mesh), HK_NULL },
	{ "materials", HK_NULL, HK_NULL, hkClassMember::TYPE_ARRAY, hkClassMember::TYPE_POINTER, 0, 0|hkClassMember::SERIALIZE_IGNORED, HK_OFFSET_OF(hkVisionMeshShape,m_materials), HK_NULL },
	{ "sections", HK_NULL, HK_NULL, hkClassMember::TYPE_ARRAY, hkClassMember::TYPE_VOID, 0, 0|hkClassMember::SERIALIZE_IGNORED, HK_OFFSET_OF(hkVisionMeshShape,m_sections), HK_NULL },
	{ "isBaked", HK_NULL, HK_NULL, hkClassMember::TYPE_BOOL, hkClassMember::TYPE_VOID, 0, 0|hkClassMember::SERIALIZE_IGNORED, HK_OFFSET_OF(hkVisionMeshShape,m_isBaked), HK_NULL }
};
extern const hkClass hkVisionMeshShapeClass;
const hkClass hkVisionMeshShapeClass(
	"hkVisionMeshShape",
	&hkxBlobMeshShapeClass, // parent
	sizeof(::hkVisionMeshShape),
	HK_NULL,
	0, // interfaces
	HK_NULL,
	0, // enums
	reinterpret_cast<const hkClassMember*>(hkVisionMeshShape::Members),
	HK_COUNT_OF(hkVisionMeshShape::Members),
	HK_NULL, // defaults
	HK_NULL, // attributes
	0, // flags
	hkUint32(0) // version
	);
#ifndef HK_HKCLASS_DEFINITION_ONLY
const hkClass& HK_CALL hkVisionMeshShape::staticClass()
{
	return hkVisionMeshShapeClass;
}
HK_COMPILE_TIME_ASSERT2( \
	sizeof(hkIsVirtual(static_cast<hkVisionMeshShape*>(0))) == sizeof(hkBool::CompileTimeTrueType), \
	REFLECTION_PARSER_VTABLE_DETECTION_FAILED );
static void HK_CALL finishLoadedObjecthkVisionMeshShape(void* p, int finishing = 1)
{
	hkFinishLoadedObjectFlag f;
	f.m_finishing = finishing;
	new (p) hkVisionMeshShape(f);
}
static void HK_CALL cleanupLoadedObjecthkVisionMeshShape(void* p)
{
	static_cast<hkVisionMeshShape*>(p)->~hkVisionMeshShape();
}
static const void* HK_CALL getVtablehkVisionMeshShape()
{
	#if HK_LINKONCE_VTABLES==0
	#if HK_HASHCODE_VTABLE_REGISTRY==1
	return ((const void*)(typeid(hkVisionMeshShape).hash_code()));
	#else
	return ((const void*)(typeid(hkVisionMeshShape).name()));
	#endif
	#else
	union { HK_ALIGN16(void* ptr); char buf[sizeof(hkVisionMeshShape)]; } u;
	hkFinishLoadedObjectFlag f;
	new (u.buf) hkVisionMeshShape(f);
	return u.ptr;
	#endif
}
extern const hkTypeInfo hkVisionMeshShapeTypeInfo;
const hkTypeInfo hkVisionMeshShapeTypeInfo(
	"hkVisionMeshShape",
	"!hkVisionMeshShape",
	finishLoadedObjecthkVisionMeshShape,
	cleanupLoadedObjecthkVisionMeshShape,
	getVtablehkVisionMeshShape(),
	sizeof(hkVisionMeshShape)
	);
#endif

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
