/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_CLASS(hkpAngularDashpotAction)
HK_CLASS(hkpBallGun)
HK_CLASS(hkpCharacterControllerCinfo)
HK_CLASS(hkpCharacterProxyCinfo)
HK_CLASS(hkpCharacterRigidBodyCinfo)
HK_CLASS(hkpConstrainedSystemFilter)
HK_CLASS(hkpDashpotAction)
HK_CLASS(hkpDisableEntityCollisionFilter)
HK_CLASS(hkpDisplayBindingData)
HK_CLASS(hkpDisplayBindingDataPhysicsSystem)
HK_CLASS(hkpDisplayBindingDataRigidBody)
HK_CLASS(hkpFirstPersonGun)
HK_CLASS(hkpGravityGun)
HK_CLASS(hkpGroupCollisionFilter)
HK_CLASS(hkpMotorAction)
HK_CLASS(hkpMountedBallGun)
HK_CLASS(hkpMouseSpringAction)
HK_CLASS(hkpPhysicsData)
HK_CLASS(hkpPhysicsSystemWithContacts)
HK_CLASS(hkpPoweredChainMapper)
HK_CLASS(hkpProjectileGun)
HK_CLASS(hkpReorientAction)
HK_CLASS(hkpSerializedAgentNnEntry)
HK_CLASS(hkpSerializedDisplayMarker)
HK_CLASS(hkpSerializedDisplayMarkerList)
HK_CLASS(hkpSerializedDisplayRbTransforms)
HK_CLASS(hkpSpringAction)
HK_CLASS(hkpTriggerVolume)
HK_STRUCT(hkpPoweredChainMapperLinkInfo)
HK_STRUCT(hkpPoweredChainMapperTarget)
HK_STRUCT(hkpSerializedDisplayRbTransformsDisplayTransformPair)
HK_STRUCT(hkpSerializedSubTrack1nInfo)
HK_STRUCT(hkpSerializedTrack1nInfo)
HK_STRUCT(hkpTriggerVolumeEventInfo)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
