/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_ABSTRACT_CLASS(hkpVehicleAerodynamics)
HK_ABSTRACT_CLASS(hkpVehicleBrake)
HK_ABSTRACT_CLASS(hkpVehicleCastBatchingManager)
HK_ABSTRACT_CLASS(hkpVehicleDriverInput)
HK_ABSTRACT_CLASS(hkpVehicleDriverInputStatus)
HK_ABSTRACT_CLASS(hkpVehicleEngine)
HK_ABSTRACT_CLASS(hkpVehicleSteering)
HK_ABSTRACT_CLASS(hkpVehicleSuspension)
HK_ABSTRACT_CLASS(hkpVehicleTransmission)
HK_ABSTRACT_CLASS(hkpVehicleVelocityDamper)
HK_ABSTRACT_CLASS(hkpVehicleWheelCollide)
HK_CLASS(hkpMultithreadedVehicleManager)
HK_CLASS(hkpRejectChassisListener)
HK_CLASS(hkpTyremarksInfo)
HK_CLASS(hkpTyremarksWheel)
HK_CLASS(hkpVehicleData)
HK_CLASS(hkpVehicleDefaultAerodynamics)
HK_CLASS(hkpVehicleDefaultAnalogDriverInput)
HK_CLASS(hkpVehicleDefaultBrake)
HK_CLASS(hkpVehicleDefaultEngine)
HK_CLASS(hkpVehicleDefaultSteering)
HK_CLASS(hkpVehicleDefaultSuspension)
HK_CLASS(hkpVehicleDefaultTransmission)
HK_CLASS(hkpVehicleDefaultVelocityDamper)
HK_CLASS(hkpVehicleDriverInputAnalogStatus)
HK_CLASS(hkpVehicleInstance)
HK_CLASS(hkpVehicleLinearCastBatchingManager)
HK_CLASS(hkpVehicleLinearCastWheelCollide)
HK_CLASS(hkpVehicleManager)
HK_CLASS(hkpVehicleRayCastBatchingManager)
HK_CLASS(hkpVehicleRayCastWheelCollide)
HK_STRUCT(hkpTyremarkPoint)
HK_STRUCT(hkpVehicleDataWheelComponentParams)
HK_STRUCT(hkpVehicleDefaultBrakeWheelBrakingProperties)
HK_STRUCT(hkpVehicleDefaultSuspensionWheelSpringSuspensionParameters)
HK_STRUCT(hkpVehicleInstanceWheelInfo)
HK_STRUCT(hkpVehicleLinearCastWheelCollideWheelState)
HK_STRUCT(hkpVehicleSuspensionSuspensionWheelParameters)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
