/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_CLASS(hkcdDynamicAabbTree)
HK_CLASS(hkcdStaticAabbTree)
HK_STRUCT(hkcdDynamicTreeAnisotropicMetric)
HK_STRUCT(hkcdDynamicTreeBalanceMetric)
HK_STRUCT(hkcdDynamicTreeCentroidMetric)
HK_STRUCT(hkcdDynamicTreeCodec18)
HK_STRUCT(hkcdDynamicTreeCodec32)
HK_STRUCT(hkcdDynamicTreeCodecInt16)
HK_STRUCT(hkcdDynamicTreeCodecInt16IntAabb)
HK_STRUCT(hkcdDynamicTreeCodecRawUint)
HK_STRUCT(hkcdDynamicTreeCodecRawUlong)
HK_STRUCT(hkcdDynamicTreeCodecRawunsignedint)
HK_STRUCT(hkcdDynamicTreeCodecRawunsignedlong)
HK_STRUCT(hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodec32)
HK_STRUCT(hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecInt16)
HK_STRUCT(hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUint)
HK_STRUCT(hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUlong)
HK_STRUCT(hkcdDynamicTreeDefaultTree32Storage)
HK_STRUCT(hkcdDynamicTreeDefaultTree48Storage)
HK_STRUCT(hkcdDynamicTreeDefaultTreeInt16Storage)
HK_STRUCT(hkcdDynamicTreeDefaultTreePtrStorage)
HK_STRUCT(hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodec32)
HK_STRUCT(hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodecInt16)
HK_STRUCT(hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodecRawUint)
HK_STRUCT(hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodecRawUlong)
HK_STRUCT(hkcdDynamicTreeDynamicStorage16)
HK_STRUCT(hkcdDynamicTreeDynamicStorage32)
HK_STRUCT(hkcdDynamicTreeDynamicStorageInt16)
HK_STRUCT(hkcdDynamicTreeDynamicStoragePtr)
HK_STRUCT(hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorage16)
HK_STRUCT(hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorage32)
HK_STRUCT(hkcdDynamicTreeTreehkcdDynamicTreeDynamicStorageInt16)
HK_STRUCT(hkcdDynamicTreeTreehkcdDynamicTreeDynamicStoragePtr)
HK_STRUCT(hkcdStaticMeshTreeBase)
HK_STRUCT(hkcdStaticMeshTreeBasePrimitive)
HK_STRUCT(hkcdStaticMeshTreeBasePrimitiveDataRunBaseunsignedshort)
HK_STRUCT(hkcdStaticMeshTreeBaseSection)
HK_STRUCT(hkcdStaticMeshTreeBaseSectionDataRuns)
HK_STRUCT(hkcdStaticMeshTreeBaseSectionPrimitives)
HK_STRUCT(hkcdStaticMeshTreeBaseSectionSharedVertices)
HK_STRUCT(hkcdStaticMeshTreeDefaultDataRun)
HK_STRUCT(hkcdStaticPvs)
HK_STRUCT(hkcdStaticPvsBlockHeader)
HK_STRUCT(hkcdStaticTreeCodec3Axis)
HK_STRUCT(hkcdStaticTreeCodec3Axis4)
HK_STRUCT(hkcdStaticTreeCodec3Axis5)
HK_STRUCT(hkcdStaticTreeCodec3Axis6)
HK_STRUCT(hkcdStaticTreeCodecRaw)
HK_STRUCT(hkcdStaticTreeDefaultTreeStorage32)
HK_STRUCT(hkcdStaticTreeDefaultTreeStorage4)
HK_STRUCT(hkcdStaticTreeDefaultTreeStorage5)
HK_STRUCT(hkcdStaticTreeDefaultTreeStorage6)
HK_STRUCT(hkcdStaticTreeDynamicStorage32)
HK_STRUCT(hkcdStaticTreeDynamicStorage4)
HK_STRUCT(hkcdStaticTreeDynamicStorage5)
HK_STRUCT(hkcdStaticTreeDynamicStorage6)
HK_STRUCT(hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis4)
HK_STRUCT(hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis5)
HK_STRUCT(hkcdStaticTreeDynamicStoragehkcdStaticTreeCodec3Axis6)
HK_STRUCT(hkcdStaticTreeDynamicStoragehkcdStaticTreeCodecRaw)
HK_STRUCT(hkcdStaticTreeTreehkcdStaticTreeDynamicStorage32)
HK_STRUCT(hkcdStaticTreeTreehkcdStaticTreeDynamicStorage4)
HK_STRUCT(hkcdStaticTreeTreehkcdStaticTreeDynamicStorage5)
HK_STRUCT(hkcdStaticTreeTreehkcdStaticTreeDynamicStorage6)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
