/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */
//
// NOTE: This file is autogenerated. Any changes will be lost.
//
//HK_REFLECTION_PARSER_EXCLUDE_FILE
HK_TEST_DECLARE(BoxBoxTest)
HK_TEST_DECLARE(ExtremeCasesGskTest)
HK_TEST_DECLARE(shapeCollectionCastRay_main)
HK_TEST_DECLARE(spherebox_main)
HK_TEST_DECLARE(aabb_main)
HK_TEST_DECLARE(ContinuousGskTest_main)
HK_TEST_DECLARE(degenerate_triangles)
HK_TEST_DECLARE(mopp_main)
HK_TEST_DECLARE(MultiplePenetrationTest_main)
HK_TEST_DECLARE(broadphaseBatchAddTest_main)
HK_TEST_DECLARE(broadphaseRaycast_main)
HK_TEST_DECLARE(fixedBufferCdPointCollector_test)
HK_TEST_DECLARE(bundle_raycast_test)
HK_TEST_DECLARE(CylinderShapeUnitTest)
HK_TEST_DECLARE(test_get_shape_type_name)
HK_TEST_DECLARE(hkpConvexTransformShapeUnitTest)
HK_TEST_DECLARE(hkMeshShape_degenerate_test)
HK_TEST_DECLARE(raycast_test)
HK_TEST_DECLARE(ShapeInterfaceUnitTest)
HK_TEST_DECLARE(SphereCast_test)
HK_TEST_DECLARE(tricontainspoint_main)
HK_TEST_DECLARE(degeneracy_main)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
