/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

/// \file VisApiProfElements.hpp

#ifndef DEFINE_VISAPIPROFELEMENTS
#define DEFINE_VISAPIPROFELEMENTS


/// \brief Performance Counter Types
enum
{
  VIS_PERFCNT_DRAWCALLS = 0,
  VIS_PROFCNT_IMDRAWCALLS = 1,
  VIS_PROFCNT_STATE_TEXTURECHG = 2,
  VIS_PROFCNT_STATE_SG_SAMPLER = 3,
  VIS_PROFCNT_STATE_SG_BLEND = 4,
  VIS_PROFCNT_STATE_SG_RASTERIZER = 5,
  VIS_PROFCNT_STATE_SG_DEPTHSTENCIL = 6,
  VIS_PROFCNT_VS = 7,
  VIS_PROFCNT_PS = 8,
  VIS_PROFCNT_VSCONST = 9,
  VIS_PROFCNT_PSCONST = 10,
  VIS_PROFCNT_ATTRIBSETUP = 11,
  VIS_PROFCNT_RECOMPUTEVISIBILITYZONE = 12,
  VIS_PROFCNT_RENDERED_PARTICLES = 13
};


/// \brief Real-time Profiling
enum 
{
  VIS_PROFILE_SINCELASTFRAME=256,
  VIS_PROFILE_OVERALLRENDERING,
  VIS_PROFILE_MASKS,
  VIS_PROFILE_HWREND_RENDERDEBUGINFO,
  VIS_PROFILE_HARDWARERENDERING,
  VIS_PROFILE_RENDERLINES,
  VIS_PROFILE_MISCELLANEOUS,
  VIS_PROFILE_DISPLAYING,
  VIS_PROFILE_CUSTOMRENDERLOOP,
  VIS_PROFILE_HWREND_CLEARSCREEN,
  VIS_PROFILE_VIS_FETCHOCCLUSIONTESTS,
  VIS_PROFILE_SWREND_HANDLELIGHTS,
  VIS_PROFILE_SWREND_POLYSHADOWS,
  VIS_PROFILE_ENTITY_BASE,
  VIS_PROFILE_ENTITY_SHADERS,
  VIS_PROFILE_ENTITY_SURFACESHADERLIST,
  VIS_PROFILE_ENTITY_LIGHTINFLUENCE,
  VIS_PROFILE_ENTITY_UPDATELIGHTINFLUENCE,
  VIS_PROFILE_ENTITY_CREATELIGHTINFLUENCE,
  VIS_PROFILE_HWREND_MISCELLANEOUS,
  VIS_PROFILE_HWREND_SORTSHADOWPOLYS,
  VIS_PROFILE_HWREND_POLYINFO,
  VIS_PROFILE_HWREND_SKY,
  VIS_PROFILE_HWREND_BUMPMAPS,
  VIS_PROFILE_TRACKLIGHTGRID,
  VIS_PROFILE_HWREND_PARTICLES,
  VIS_PROFILE_HWREND_SPECULARINTERPOLATIONS,
  VIS_PROFILE_HWREND_SPECULARMAPPING,
  VIS_PROFILE_HWREND_POLYSHADOWS,
  VIS_PROFILE_POLYGONALSHADOWS,
  VIS_PROFILE_OBJECT_BONEMATRICES,
  VIS_PROFILE_STATICMESH_COLLISIONMESH,
  VIS_PROFILE_ENTITY_COLLISIONMESH,
  VIS_PROFILE_CONVEXVOLUMES,
  VIS_PROFILE_VIS_OVERALL,
  VIS_PROFILE_VIS_ONDOVISIBILITY,
  VIS_PROFILE_VIS_NODETRANSITIONS,
  VIS_PROFILE_VIS_POSTPROCESS,
  VIS_PROFILE_VIS_SCHEDULEOCCLUSIONTESTS,
  VIS_PROFILE_GLFINISH,
  VIS_PROFILE_GAMELOOP,
  VIS_PROFILE_VIS_SKYVIS,
  VIS_PROFILE_CPP_HANDLELIGHTSOURCES,
  VIS_PROFILE_OBJECTDRAWING_CREATEMATRICES,
  VIS_PROFILE_OBJECTDRAWING_LOD,
  //VIS_PROFILE_OBJECTDRAWING_FLAGIRRELEVANT=382,
  VIS_PROFILE_OBJECTDRAWING_ADDTOCACHE,
  VIS_PROFILE_OBJECTDRAWING_MUSCLEANIMS,
  VIS_PROFILE_PREPAREOBJECT,
  VIS_PROFILE_DRAWOBJECT,
  VIS_PROFILE_OBJECTDRAWING_OVERLAYS,
  VIS_PROFILE_OBJECTDRAWING_DRAWSIMPLECHUNK,
  VIS_PROFILE_OBJECTDRAWING_SKINNING,
  VIS_PROFILE_OBJECTDRAWING_GLMATRIX,
  VIS_PROFILE_OBJECTDRAWING_STATESETUP,
  VIS_PROFILE_OBJECTDRAWING_SORTING,
  VIS_PROFILE_TRANSPOLYSORTING,
  VIS_PROFILE_DEBUGLINES,
  VIS_PROFILE_FSQUAD,
  VIS_PROFILE_VISFROMLIGHT,
  VIS_PROFILE_VISFROMLIGHTRANGE,
  VIS_PROFILE_VISFROMSTATICLIGHTTABLE,
  VIS_PROFILE_MOSTRELEVANTDYNLIGHTS,
  VIS_PROFILE_TEMP_01,
  VIS_PROFILE_TEMP_02,
  VIS_PROFILE_TEMP_03,
  VIS_PROFILE_TEMP_04,
  VIS_PROFILE_TEMP_05,
  VIS_PROFILE_TEMP_06,
  VIS_PROFILE_TEMP_07,
  VIS_PROFILE_TEMP_08,
  VIS_PROFILE_OBJECTDRAWING_MATERIALSETUP,
  VIS_PROFILE_OBJECTDRAWING_LIGHTSETUP,
  VIS_PROFILE_OBJECTDRAWING_XFER,
  VIS_PROFILE_CURVES_XFER,
  VIS_PROFILE_HEIGHTFIELD_XFER,
  VIS_PROFILE_HWREND_SHADERS,
  VIS_PROFILE_SHADERS_TEXTURESETUP,
  VIS_PROFILE_SHADERS_STATESETUP,
  VIS_PROFILE_SHADERS_STATEINIT,
  VIS_PROFILE_SHADERS_GENCUBEMAP,
  VIS_PROFILE_SHADERS_ONHEIGHTFIELDS,
  VIS_PROFILE_SHADERS_ONMODELS,
  VIS_PROFILE_RENDERTOTEXTURE,
  VIS_PROFILE_POLYGONS_COLLISIONMESH,
  //VIS_PROFILE_HWOCCTEST_START=635,
  //VIS_PROFILE_HWOCCTEST_QUERY=636,
  //VIS_PROFILE_HWOCCTEST_VISIBILITYOBJECTS=637,
  VIS_PROFILE_HWREND_VERTEXBUFFER_OVERALL,
  VIS_PROFILE_HWREND_VERTEXBUFFER_RENDERING,
  //VIS_PROFILE_VIS_COMPRESSPOLYGONLIST=642,
  VIS_PROFILE_RESOURCE_HANDLE_ALL,
  VIS_PROFILE_RESOURCE_CHECK_FOR_CHANGES,
  VIS_PROFILE_RESOURCE_UPDATE_VIEWER,
  VIS_PROFILE_CONTEXTSWITCHES,
  VIS_PROFILE_HWREND_VERTEXBUFFER_SORTING,
  VIS_PROFILE_HWREND_VERTEXBUFFER_TEXTURESETUP,
  VIS_PROFILE_HWREND_VERTEXBUFFER_SHADERTEXTURESETUP,
  VIS_PROFILE_HWREND_VERTEXBUFFER_MATRIXSETUP,
  VIS_PROFILE_HWREND_VERTEXBUFFER_DRAWPRIMITIVES,
  VIS_PROFILE_HWREND_VERTEXBUFFER_ADDBUFFERSTREAMS,
  VIS_PROFILE_HWREND_VERTEXBUFFER_DIRECTRENDERING,

  VIS_PROFILE_STATICMESH_SURFACESHADERS,
  VIS_PROFILE_STATICMESH_SPECIFICSHADERS,

  VIS_PROFILE_LOWLEVELRENDERER_SETVERTEXBUFFER, 
  VIS_PROFILE_LOWLEVELRENDERER_BUILDVERTEXDECL, 

  VIS_PROFILE_ANIMSYS_OVERALL,
  VIS_PROFILE_ANIMSYS_SKELETAL_OVERALL,
  VIS_PROFILE_ANIMSYS_VERTEX_OVERALL,
  VIS_PROFILE_ANIMSYS_STATE_OVERALL,
  VIS_PROFILE_ANIMSYS_RESULT_OVERALL,
  VIS_PROFILE_ANIMSYS_STATE_SKELETAL_OVERALL,
  VIS_PROFILE_ANIMSYS_STATE_SKELETAL_TREE,
  VIS_PROFILE_ANIMSYS_STATE_SKELETAL_ANIM,
  VIS_PROFILE_ANIMSYS_RESULT_SKELETAL_OVERALL,
  VIS_PROFILE_ANIMSYS_RESULT_SKELETAL_TREE,
  VIS_PROFILE_ANIMSYS_RESULT_SKELETAL_ANIM,
  VIS_PROFILE_ANIMSYS_SKELETAL_REMAPPING,
  VIS_PROFILE_ANIMSYS_STATE_VERTEX_OVERALL,
  VIS_PROFILE_ANIMSYS_STATE_VERTEX_OVERHEAD,
  VIS_PROFILE_ANIMSYS_STATE_VERTEX_ANIM,
  VIS_PROFILE_ANIMSYS_STATE_VERTEX_SKINNING,
  VIS_PROFILE_ANIMSYS_RESULT_VERTEX_OVERALL,
  VIS_PROFILE_ANIMSYS_RESULT_VERTEX_OVERHEAD,
  VIS_PROFILE_ANIMSYS_RESULT_VERTEX_ANIM,
  VIS_PROFILE_ANIMSYS_RESULT_VERTEX_SKINNING,
  VIS_PROFILE_ANIMSYS_RESULT_VERTEX_WAITFORSPU,
  VIS_PROFILE_ANIMSYS_RESULT_VERTEX_KICKOFFSPU,
  VIS_PROFILE_ANIMSYS_EXTRA,
  VIS_PROFILE_ANIMSYS_TRACKSHADERCONSTANTS, 
  VIS_PROFILE_ANIMSYS_MEMEXPORTSKINNING,

  VIS_PROFILE_LG_TRACKENTITY_INFO,
  VIS_PROFILE_LG_LIGHTGRID_LOOKUP,
  VIS_PROFILE_LG_TRACKSHADER,

  // 2D rendering
  VIS_PROFILE_2D_DRAWBUFFER,
  VIS_PROFILE_2D_DRAWBUFFERWITHSHADER,
  VIS_PROFILE_2D_FONTRENDERING,

  // streaming
  VIS_PROFILE_STREAMING_OVERALL,
  VIS_PROFILE_STREAMING_CREATOR_FIND,
  VIS_PROFILE_STREAMING_CREATOR_CREATE,
  VIS_PROFILE_STREAMING_HANDLE_ZONES,
  VIS_PROFILE_STREAMING_LOAD_SNAPSHOT,
  VIS_PROFILE_STREAMING_SNAPSHOT_TICK,
  VIS_PROFILE_STREAMING_INSTANCE_TICK,
  VIS_PROFILE_STREAMING_ZONE_RELOAD,
  VIS_PROFILE_STREAMING_ZONE_UNLOAD,
  VIS_PROFILE_STREAMING_ZONE_LOADREMAINING,
  VIS_PROFILE_STREAMING_PURGE_RESOURCES,
  VIS_PROFILE_STREAMING_LOADMODEL_OVERALL,
  VIS_PROFILE_STREAMING_LOADMODEL_MATERIALS,
  VIS_PROFILE_STREAMING_LOADMODEL_OPENFILE,
  VIS_PROFILE_STREAMING_LOADMODEL_OPENALLCHUNKS,
  VIS_PROFILE_STREAMING_LOADMODEL_FINISH,
  VIS_PROFILE_STREAMING_LOADMODEL_SKELETONCHUNK,
  VIS_PROFILE_STREAMING_LOADMODEL_GEOMINFOCHUNK,
  VIS_PROFILE_STREAMING_LOADMODEL_WEIGHTCHUNK,
  VIS_PROFILE_STREAMING_LOADMODEL_BBOXCHUNK,
  VIS_PROFILE_STREAMING_LOADMODEL_EXTENTCHUNK,
  VIS_PROFILE_FILEACCESS_OPEN,
  VIS_PROFILE_FILEACCESS_EXISTS,
  VIS_PROFILE_REPOSITION_BACKUP,
  VIS_PROFILE_REPOSITION_ONREPOSITION,
  VIS_PROFILE_REPOSITION_CUSTOMOBJECTS,

  // more subgroups of VIS_PROFILE_STREAMING_CREATOR_CREATE
  VIS_PROFILE_STREAMING_CREATOR_CREATETEXTURE,
  VIS_PROFILE_STREAMING_CREATOR_CREATEANIM,
  VIS_PROFILE_STREAMING_CREATOR_CREATESHADERLIB,
  VIS_PROFILE_STREAMING_CREATOR_CREATESTATICMESH,


  // callbacks
  VIS_PROFILE_CALLBACKS_UNCOVERED,
  VIS_PROFILE_CALLBACKS_WORLDINIT,
  VIS_PROFILE_CALLBACKS_WORLDDEINIT,
  VIS_PROFILE_CALLBACKS_PROGRESS,
  VIS_PROFILE_CALLBACKS_UPDATESCENEBEGIN,
  VIS_PROFILE_CALLBACKS_UPDATESCENEFINISHED,
  VIS_PROFILE_CALLBACKS_ENGINEINIT,
  VIS_PROFILE_CALLBACKS_ENGINEDEINIT,
  VIS_PROFILE_CALLBACKS_NEWMODELLOADED,
  VIS_PROFILE_CALLBACKS_NEWMESHLOADED,
  VIS_PROFILE_CALLBACKS_TEXTURELOADING,
  VIS_PROFILE_CALLBACKS_RENDERHOOK,
  VIS_PROFILE_CALLBACKS_CONTEXTSWITCHED,
  VIS_PROFILE_CALLBACKS_CONTEXTSWITCHING,
  VIS_PROFILE_CALLBACKS_RENDERERNODESWITCHING,
  VIS_PROFILE_CALLBACKS_VISIBILITYPERFORMED,
  VIS_PROFILE_CALLBACKS_VIDEOCHANGED,
  VIS_PROFILE_CALLBACKS_EDITORMODECHANGED,
  VIS_PROFILE_CALLBACKS_BEFORESCENELOADED,
  VIS_PROFILE_CALLBACKS_AFTERSCENELOADED,
  VIS_PROFILE_CALLBACKS_LEAVEFOREGROUND,
  VIS_PROFILE_CALLBACKS_ENTERBACKGROUND,
  VIS_PROFILE_CALLBACKS_LEAVEBACKGROUND,
  VIS_PROFILE_CALLBACKS_ENTERFOREGROUND,
  VIS_PROFILE_CALLBACKS_BACKGROUNDRESTORE,
  VIS_PROFILE_CALLBACKS_REASSIGNSHADERS,
  VIS_PROFILE_CALLBACKS_SCRIPTTHINK,
  VIS_PROFILE_CALLBACKS_STARTVISIBILITYDETERMINATION,
  VIS_PROFILE_CALLBACKS_FINISHVISIBILITYDETERMINATION,

  VIS_PROFILE_HWREND_VERTEXBUFFER_BEGINENDMESHRENDERING,
  VIS_PROFILE_RINGBUFFER_MAP_UNMAP,
  VIS_PROFILE_RINGBUFFER_SYNC,

  VIS_PROFILE_HWREND_COMPUTE,

  // PS3 GCM
  VIS_PROFILE_GCM_FRAGMENTSHADERPATCHING,
  VIS_PROFILE_GCM_FRAGMENTSHADERPATCHING_WAITRSX,

  // WiiU
  VIS_PROFILE_WIIU_WAITGPU,

  // APP Callbacks
  VIS_PROFILE_CALLBACKS_UPDATEANIMATIONFINISHED,
  VIS_PROFILE_CALLBACKS_UPDATEPHYSICSFINISHED,
  VIS_PROFILE_CALLBACKS_UPDATEANIMATIONBEGIN

};

#endif

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
