/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_ABSTRACT_CLASS(hkaiAstarCostModifier)
HK_ABSTRACT_CLASS(hkaiAstarEdgeFilter)
HK_ABSTRACT_CLASS(hkaiNavMeshQueryMediator)
HK_ABSTRACT_CLASS(hkaiNavVolumeMediator)
HK_ABSTRACT_CLASS(hkaiObstacleGenerator)
HK_ABSTRACT_CLASS(hkaiPhysicsBodySilhouetteGeneratorBase)
HK_ABSTRACT_CLASS(hkaiSilhouetteGenerator)
HK_ABSTRACT_CLASS(hkaiVolume)
HK_CLASS(hkaiAabbTreeNavVolumeMediator)
HK_CLASS(hkaiAvoidancePairProperties)
HK_CLASS(hkaiAvoidanceProperties)
HK_CLASS(hkaiCharacter)
HK_CLASS(hkaiConvexHullSilhouetteMerger)
HK_CLASS(hkaiConvexSilhouetteSet)
HK_CLASS(hkaiCuttingGeometryInfo)
HK_CLASS(hkaiDefaultAstarCostModifier)
HK_CLASS(hkaiDefaultAstarEdgeFilter)
HK_CLASS(hkaiDirectedGraphExplicitCost)
HK_CLASS(hkaiDirectedGraphInstance)
HK_CLASS(hkaiDynamicNavMeshQueryMediator)
HK_CLASS(hkaiDynamicNavVolumeMediator)
HK_CLASS(hkaiEdgePath)
HK_CLASS(hkaiInvertedAabbVolume)
HK_CLASS(hkaiMaterialPainter)
HK_CLASS(hkaiNavMesh)
HK_CLASS(hkaiNavMeshCutter)
HK_CLASS(hkaiNavMeshInstance)
HK_CLASS(hkaiNavMeshPathRequestInfo)
HK_CLASS(hkaiNavVolume)
HK_CLASS(hkaiNavVolumeInstance)
HK_CLASS(hkaiNavVolumePathRequestInfo)
HK_CLASS(hkaiOverlapManager)
HK_CLASS(hkaiOverlapManagerSectionGeneratorData)
HK_CLASS(hkaiPath)
HK_CLASS(hkaiPathFollowingProperties)
HK_CLASS(hkaiPathfindingUtilFindPathInput)
HK_CLASS(hkaiPathfindingUtilFindPathOutput)
HK_CLASS(hkaiPlaneVolume)
HK_CLASS(hkaiPointCloudSilhouetteGenerator)
HK_CLASS(hkaiSilhouetteMerger)
HK_CLASS(hkaiSimpleObstacleGenerator)
HK_CLASS(hkaiSimpleSilhouetteMerger)
HK_CLASS(hkaiStaticTreeNavMeshQueryMediator)
HK_CLASS(hkaiStreamingCollection)
HK_CLASS(hkaiUserEdgePairArray)
HK_CLASS(hkaiUserEdgeSetupArray)
HK_CLASS(hkaiVolumePathfindingUtilFindPathInput)
HK_CLASS(hkaiVolumePathfindingUtilFindPathOutput)
HK_CLASS(hkaiWorld)
HK_CLASS(hkaiWorldCharacterStepSerializableContext)
HK_STRUCT(hkaiAdaptiveRanger)
HK_STRUCT(hkaiAgentTraversalInfo)
HK_STRUCT(hkaiAstarOutputParameters)
HK_STRUCT(hkaiAvoidancePairPropertiesPairData)
HK_STRUCT(hkaiAvoidanceSolverBoundaryObstacle)
HK_STRUCT(hkaiAvoidanceSolverSphereObstacle)
HK_STRUCT(hkaiDirectedGraphExplicitCostEdge)
HK_STRUCT(hkaiDirectedGraphExplicitCostNode)
HK_STRUCT(hkaiDirectedGraphInstanceFreeBlockList)
HK_STRUCT(hkaiEdgePathEdge)
HK_STRUCT(hkaiEdgePathFollowingCornerInfo)
HK_STRUCT(hkaiGraphPathSearchParameters)
HK_STRUCT(hkaiHierarchyUtils)
HK_STRUCT(hkaiHierarchyUtilsClusterSettings)
HK_STRUCT(hkaiLineOfSightUtil)
HK_STRUCT(hkaiLineOfSightUtilDirectPathInput)
HK_STRUCT(hkaiLineOfSightUtilInputBase)
HK_STRUCT(hkaiLineOfSightUtilLineOfSightInput)
HK_STRUCT(hkaiLineOfSightUtilLineOfSightOutput)
HK_STRUCT(hkaiLocalSteeringInput)
HK_STRUCT(hkaiMovementProperties)
HK_STRUCT(hkaiNavMeshCutterMeshInfo)
HK_STRUCT(hkaiNavMeshCutterSavedConnectivity)
HK_STRUCT(hkaiNavMeshEdge)
HK_STRUCT(hkaiNavMeshFace)
HK_STRUCT(hkaiNavMeshGenerationSnapshot)
HK_STRUCT(hkaiNavMeshPathSearchParameters)
HK_STRUCT(hkaiNavVolumeCell)
HK_STRUCT(hkaiNavVolumeEdge)
HK_STRUCT(hkaiNavVolumeGenerationSnapshot)
HK_STRUCT(hkaiNavVolumeInstanceCellInstance)
HK_STRUCT(hkaiNavVolumePathSearchParameters)
HK_STRUCT(hkaiOverlapManagerSection)
HK_STRUCT(hkaiPathPathPoint)
HK_STRUCT(hkaiPathfindingUtil)
HK_STRUCT(hkaiPathfindingUtilFindGraphPathInput)
HK_STRUCT(hkaiPersistentEdgeKey)
HK_STRUCT(hkaiPersistentFaceKey)
HK_STRUCT(hkaiReferenceFrame)
HK_STRUCT(hkaiReferenceFrameAndExtrusion)
HK_STRUCT(hkaiSilhouetteGenerationParameters)
HK_STRUCT(hkaiSilhouetteGeneratorSectionContext)
HK_STRUCT(hkaiSilhouetteReferenceFrame)
HK_STRUCT(hkaiSplitGenerationSnapshot)
HK_STRUCT(hkaiSplitGenerationUtils)
HK_STRUCT(hkaiSplitGenerationUtilsSettings)
HK_STRUCT(hkaiStreamingCollectionInstanceInfo)
HK_STRUCT(hkaiStreamingSet)
HK_STRUCT(hkaiStreamingSetGraphConnection)
HK_STRUCT(hkaiStreamingSetNavMeshConnection)
HK_STRUCT(hkaiStreamingSetVolumeConnection)
HK_STRUCT(hkaiUserEdgeUtils)
HK_STRUCT(hkaiUserEdgeUtilsObb)
HK_STRUCT(hkaiUserEdgeUtilsUserEdgePair)
HK_STRUCT(hkaiUserEdgeUtilsUserEdgeSetup)
HK_STRUCT(hkaiVolumePathfindingUtil)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
