/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_ABSTRACT_CLASS(hkbPhysicsInterface)
HK_ABSTRACT_CLASS(hkbRagdollInterface)
HK_CLASS(hkbAiControlCancelPathCommand)
HK_CLASS(hkbAiControlPathToCommand)
HK_CLASS(hkbAlignBoneModifier)
HK_CLASS(hkbAnimatedSkeletonGenerator)
HK_CLASS(hkbAssetBundle)
HK_CLASS(hkbAuxiliaryNodeInfo)
HK_CLASS(hkbBehaviorEventsInfo)
HK_CLASS(hkbBehaviorGraphInternalStateInfo)
HK_CLASS(hkbBehaviorInfo)
HK_CLASS(hkbCameraShakeEventPayload)
HK_CLASS(hkbCameraVariablesChangedCommand)
HK_CLASS(hkbCharacterAddedInfo)
HK_CLASS(hkbCharacterControlCommand)
HK_CLASS(hkbCharacterInfo)
HK_CLASS(hkbCharacterSelectedInfo)
HK_CLASS(hkbCharacterSkinInfo)
HK_CLASS(hkbCharacterSteppedInfo)
HK_CLASS(hkbClientCharacterState)
HK_CLASS(hkbComputeWorldFromModelModifier)
HK_CLASS(hkbCustomTestGenerator)
HK_CLASS(hkbEventRaisedInfo)
HK_CLASS(hkbGravityModifier)
HK_CLASS(hkbHoldFromBlendingTransitionEffect)
HK_CLASS(hkbLinkedSymbolInfo)
HK_CLASS(hkbNullPhysicsInterface)
HK_CLASS(hkbParticleSystemEventPayload)
HK_CLASS(hkbPinBonesGenerator)
HK_CLASS(hkbPoseStoringGeneratorOutputListener)
HK_CLASS(hkbPoseStoringGeneratorOutputListenerStoredPose)
HK_CLASS(hkbRadialSelectorGenerator)
HK_CLASS(hkbRaiseEventCommand)
HK_CLASS(hkbRebuildScriptsCommand)
HK_CLASS(hkbSetBehaviorCommand)
HK_CLASS(hkbSetLocalTimeOfClipGeneratorCommand)
HK_CLASS(hkbSetNodePropertyCommand)
HK_CLASS(hkbSetSelectedCharacterCommand)
HK_CLASS(hkbSetWordVariableCommand)
HK_CLASS(hkbSimulationControlCommand)
HK_CLASS(hkbSimulationStateInfo)
HK_CLASS(hkbStateDependentModifier)
HK_CLASS(hkbTestStateChooser)
HK_STRUCT(hkVariableTweakingHelper)
HK_STRUCT(hkVariableTweakingHelperBoolVariableInfo)
HK_STRUCT(hkVariableTweakingHelperIntVariableInfo)
HK_STRUCT(hkVariableTweakingHelperRealVariableInfo)
HK_STRUCT(hkVariableTweakingHelperVector4VariableInfo)
HK_STRUCT(hkbAssetBundleStringData)
HK_STRUCT(hkbBehaviorInfoIdToNamePair)
HK_STRUCT(hkbCharacterControllerSetup)
HK_STRUCT(hkbConstraintSetup)
HK_STRUCT(hkbCustomTestGeneratorStruck)
HK_STRUCT(hkbRadialSelectorGeneratorGeneratorInfo)
HK_STRUCT(hkbRadialSelectorGeneratorGeneratorPair)
HK_STRUCT(hkbRagdollControllerSetup)
HK_STRUCT(hkbRigidBodySetup)
HK_STRUCT(hkbShapeSetup)
HK_STRUCT(hkbToolNodeType)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
