/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */
//
// NOTE: This file is autogenerated. Any changes will be lost.
//
//HK_REFLECTION_PARSER_EXCLUDE_FILE
HK_TEST_DECLARE(astar_main)
HK_TEST_DECLARE(directedGraphMain)
HK_TEST_DECLARE(LineOfSightUtil_main)
HK_TEST_DECLARE(Convex2dUtilsTests_main)
HK_TEST_DECLARE(math2dTests_main)
HK_TEST_DECLARE(emptyNavMeshMain)
HK_TEST_DECLARE(nav_mesh_gen_utils_main)
HK_TEST_DECLARE(navMeshInputValidationTest_main)
HK_TEST_DECLARE(nav_mesh_utils_main)
HK_TEST_DECLARE(nonplanar_cast_test)
HK_TEST_DECLARE(testCalcTangentDirs)
HK_TEST_DECLARE(testCalcForwardVector)
HK_TEST_DECLARE(testLocalSteeringUtils)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
