/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */
//
// NOTE: This file is autogenerated. Any changes will be lost.
//
//HK_REFLECTION_PARSER_EXCLUDE_FILE
HK_TEST_DECLARE(testCarvers)
HK_TEST_DECLARE(testMaterialMap)
HK_TEST_DECLARE(testVoxels)
HK_TEST_DECLARE(intervalPartition_trivial)
HK_TEST_DECLARE(intervalPartition_findInterval)
HK_TEST_DECLARE(intervalPartition_lessAll1)
HK_TEST_DECLARE(intervalPartition_lessAll2)
HK_TEST_DECLARE(intervalPartition_fillGap)
HK_TEST_DECLARE(intervalPartition_lessMiddle)
HK_TEST_DECLARE(intervalPartition_greaterMiddle)
HK_TEST_DECLARE(intervalPartition_intersectMiddle1)
HK_TEST_DECLARE(intervalPartition_intersectMiddle2)
HK_TEST_DECLARE(intervalPartition_sawtooth)
HK_TEST_DECLARE(intervalPartition_extrudeX)
HK_TEST_DECLARE(intervalPartition_clipDefined1)
HK_TEST_DECLARE(intervalPartition_clipDefined2)
HK_TEST_DECLARE(intersectSweptSegmentTriangle_simple1)
HK_TEST_DECLARE(intersectSweptSegmentTriangle_diagonal)
HK_TEST_DECLARE(intersectSweptSegmentTriangle_clipPartialLeft)
HK_TEST_DECLARE(intersectSweptSegmentTriangle_clipPartialRight)
HK_TEST_DECLARE(intersectSweptSegmentTriangle_clipPartialFront)
HK_TEST_DECLARE(intersectSweptSegmentTriangle_clipPartialBack)
HK_TEST_DECLARE(intersectSweptSegmentTriangle_obliqueDisplacement)
HK_TEST_DECLARE(intersectSweptSegmentTriangle_clipTop)
HK_TEST_DECLARE(intersectSweptSegmentTriangle_clipBottom)

/*
 * Havok SDK - Base file, BUILD(#20130624)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
